name:                lagoinha-hs
version:             0.1.0.0
github:              "felipemonobe/lagoinha-hs"
license:             Unlicense
author:              "Felipe Monbe"
maintainer:          "xinube@gmail.com"
copyright:           "2019 Felipe Monobe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/felipemonobe/lagoinha-hs#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- lens
- bytestring
- xml
- aeson
- async

library:
  source-dirs: src
  default-extensions:
    - RecordWildCards
    - OverloadedStrings

executables:
  lagoinha-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - lagoinha-hs

tests:
  lagoinha-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -wall
    dependencies:
    - lagoinha-hs
